### ISSUE TITLE
CUDA error distributed training 

### ISSUE THREAD

**Issue by Songweiping** [DeMoriarty/TorchPQ#13]
Hi,

TorchPQ runs well on a single gpu, but it fails when I switch to multi-gpus. The error occurs in the synchronize step. Do you have any suggestions for multi-gpu usage?

Thanks!

**Comment by Songweiping** [comment]
Thanks for your reply. I am wondering if there is any plan on supporting distributed training? I find TorchPQ is very fast and suitable for my task, but I need distributed training as well. 

At this moment, can I move all the kmeans step to cuda:0 and move the results back to target device as a temporary solution?

**Comment by DeMoriarty** [comment]
please update torchpq to the latest version, and add
```python
device_id = 1
torchpq.kernels.set_default_device(device_id)
```
before creating any torchpq modules.

keep in mind that this is a temporary fix, and it only works under the assumption that all of your torchpq modules will be on the same device (for example running `KMeans` on cuda:0 and `IVFPQIndex` on cuda:1 is probably not going to work).

**Comment by Songweiping** [comment]
Thanks for the quick update. Will try it!
