### ISSUE TITLE
Inquiry about the centroids of the K-means method

### ISSUE THREAD

**Issue by hellodrx** [DeMoriarty/TorchPQ#16]
Hi, firstly thanks for your wonderful work. 

I want to get the centroids of the clusters and visualize them. However, from your introduction, it seems I can only get the labels of all samples. Do you have any suggestions that I can get the results? 

Thanks again for helping me out.

**Comment by hellodrx** [comment]
Is this the function I can use to get the centroids 

https://github.com/DeMoriarty/TorchPQ/blob/b8bbadf7915b8fead9a1b0f2dafa964b4058f26d/torchpq/clustering/KMeans.py#L365

**Comment by DeMoriarty** [comment]
Hi, centroids are stored in instance variable named"centroids". 
```python
kmeans = KMeans(n_clusters=4)
kmeans.fit(x)
centroids = kmeans.centroids
```

**Comment by hellodrx** [comment]
> Hi, centroids are stored in instance variable named"centroids".
> 
> ```python
> kmeans = KMeans(n_clusters=4)
> kmeans.fit(x)
> centroids = kmeans.centroids
> ```

Thank you very much!
