### ISSUE TITLE
Assertion Error

### ISSUE THREAD

**Issue by bryanhx** [DeMoriarty/TorchPQ#22]
![1](https://github.com/DeMoriarty/TorchPQ/assets/108327521/1f194c81-3312-4cb3-87f2-73f682115de7)
The assertion Error is as show in Image 1. I got max_sm_bytes = 0.

![2](https://github.com/DeMoriarty/TorchPQ/assets/108327521/8b8beb1f-359b-4d53-a724-47e781a80215)
I got value cc = [8,9] as shown in Image 2.

May I know how can I solve this issue?

**Comment by DeMoriarty** [comment]
Please upgrade to torchpq==0.3.0.6, it should be fixed.

**Comment by bryanhx** [comment]
Thank you so much for the solution.
